- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: feature
  color: 0e8a16
  description: Implement a new capability
- name: docs
  color: 0075ca
  description: Documentation improvements
- name: chore
  color: cfd3d7
  description: Routine tasks and maintenance
- name: refactor
  color: fbca04
  description: Code refactoring without behavior change
- name: ci
  color: 1d76db
  description: Continuous Integration changes
- name: dependencies
  color: 0366d6
  description: Dependency updates
- name: backend
  color: 5319e7
  description: Backend-related changes
- name: frontend
  color: 66ff66
  description: Frontend-related changes
- name: security
  color: d93f0b
  description: Security fixes or improvements
- name: question
  color: d876e3
  description: Further information requested
