[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.py$'
exclude = '(\.venv|venv|build|dist|\.mypy_cache|\.tox|\.git)'

[tool.isort]
profile = "black"
line_length = 100
skip = [".venv", "venv", "build", "dist"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503", "E501"]
exclude = [".venv", "venv", "build", "dist", ".git", "__pycache__"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
pretty = true
show_error_codes = true
warn_unused_ignores = true
exclude = '(\.venv|venv|build|dist|\.git|__pycache__)'
