name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements.txt
            frontend/requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r frontend/requirements.txt -r requirements-dev.txt

      - name: Autoflake (check)
        run: autoflake --check --remove-all-unused-imports --remove-unused-variables --expand-star-imports -r .

      - name: Ruff (lint)
        run: ruff check .

      - name: isort (check)
        run: isort --check-only .

      - name: black (check)
        run: black --check .

      - name: Flake8 (lint)
        run: flake8 .

      - name: Mypy (type check)
        run: mypy backend frontend --disable-error-code unused-ignore

      - name: Run tests
        run: pytest -q --maxfail=1
