name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt', 'frontend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r frontend/requirements.txt
          pip install black==24.4.2 isort==5.13.2 flake8==7.0.0 mypy==1.11.1 types-requests

      - name: isort (apply)
        run: isort .

      - name: black (apply)
        run: black .

      - name: Auto-commit formatting changes
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: auto-format with isort and black'

      - name: Flake8 (lint)
        run: flake8 .

      - name: Mypy (type check)
        run: mypy backend frontend
