name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements.txt
            frontend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r frontend/requirements.txt
          pip install black==24.4.2 isort==5.13.2 flake8==7.0.0 mypy==1.11.1 types-requests ruff==0.6.2 autoflake==2.3.1

      - name: Autoflake (remove unused imports/vars)
        run: autoflake --in-place --remove-all-unused-imports --remove-unused-variables --expand-star-imports -r .

      - name: Ruff (auto-fix lint)
        run: ruff check --fix .

      - name: isort (apply)
        run: isort .

      - name: black (apply)
        run: black .

      - name: Auto-commit formatting changes
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: auto-fix (autoflake, ruff) and auto-format (isort, black)'

      - name: Flake8 (lint)
        run: flake8 .

      - name: Mypy (type check)
        run: mypy backend frontend --disable-error-code unused-ignore
