name: Label PRs by paths

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

