name: Update PR branches on base changes

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Update open PR branches with latest base
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = context.ref.replace('refs/heads/', '');
            // List open PRs targeting this base branch
            const prs = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: 'open',
              base,
              per_page: 100,
            });
            core.info(`Found ${prs.length} open PR(s) targeting ${base}`);
            for (const pr of prs) {
              // Optionally skip drafts or label-filter here
              // if (pr.draft) continue;
              try {
                await github.rest.pulls.updateBranch({
                  owner,
                  repo,
                  pull_number: pr.number,
                });
                core.info(`Updated PR #${pr.number} (${pr.head.ref}) with ${base}`);
              } catch (err) {
                core.warning(`Failed to update PR #${pr.number}: ${err.message}`);
              }
            }
